config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pins

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_one_attached :image


	validate :image_type
	validates :title, :description, presence: true

	private

		def image_type
			if image.attached? == false
     			errors.add(:image, "is missing!")
   		end
   			if image.attached? == true
   				if !image.content_type.in?(%('image/jpeg image/png'))
     				errors.add(:image, "needs to be a jpeg or png!")
     		end 
   		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]


	def index 
		@pins = Pin.all.order("created_at DESC")
	end 

	def show
	end 

	def new
		@pin = current_user.pins.build
	end 

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save 
			redirect_to @pin, notice: "Successfully created new Pin"
		else 
			render 'new'
		end 
	end

	def edit
	end 

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Succesfully updated!"
		else 
			render 'edit'
		end 
	end 

	def destroy
		@pin.destroy
		redirect_to root_path
	end 

	private 

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end  

	def find_pin
		@pin = Pin.find(params[:id])
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
    def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pin Board
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  = csp_meta_tag
  = csrf_meta_tags 
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Pin Board", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Pin", new_pin_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
				=pluralize(@pin.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit Pin
	= image_tag @pin.image.variant(resize_to_fit: [400, 600])
	= render 'form'
	= link_to '<button type="button" class= "btn btn-danger">Cancel</button>'.html_safe, pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
- @pins.each do |pin|
	.box.panel.panel-default
		= link_to (image_tag pin.image.variant(resize_to_fit: [200, 300])), pin
		.panel-body
			%h2= link_to pin.title, pin

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New Form
	= render 'form'
	= link_to "Back", root_path

app/views/pins/show.html.haml
= image_tag @pin.image.variant(resize_to_fit: [400, 600])
%h1= @pin.title
%p= @pin.description

Submitted By:
%p= @pin.user.email 

%br/
= link_to '<button type="button">Back</button>'.html_safe, root_path
= link_to '<button type="button">Edit</button>'.html_safe, edit_pin_path
= link_to '<button type="button">Delete</button>'.html_safe, pin_path, method: :delete, data: { confirm: "Are you sure" }